
/**
 * FIFA three-letter codes → ISO 3166-1 alpha-2 (or UK nation tags for emoji).
 * Values are lowercase ISO codes used to build regional-indicator emoji.
 */
export const FIFA_TO_ISO: Record<string, string> = {
  AFG: 'af',
  ALB: 'al',
  ALG: 'dz',
  ASA: 'as',
  AND: 'ad',
  ANG: 'ao',
  AIA: 'ai',
  ATG: 'ag',
  ARG: 'ar',
  ARM: 'am',
  ARU: 'aw',
  AUS: 'au',
  AUT: 'at',
  AZE: 'az',
  BAH: 'bs',
  BHR: 'bh',
  BAN: 'bd',
  BRB: 'bb',
  BLR: 'by',
  BEL: 'be',
  BLZ: 'bz',
  BEN: 'bj',
  BER: 'bm',
  BHU: 'bt',
  BOL: 'bo',
  BIH: 'ba',
  BOT: 'bw',
  BRA: 'br',
  VGB: 'vg',
  BRU: 'bn',
  BUL: 'bg',
  BFA: 'bf',
  BDI: 'bi',
  CAM: 'kh',
  CMR: 'cm',
  CAN: 'ca',
  CPV: 'cv',
  CAY: 'ky',
  CTA: 'cf',
  CHA: 'td',
  CHI: 'cl',
  CHN: 'cn',
  COL: 'co',
  COM: 'km',
  CGO: 'cg',
  COK: 'ck',
  CRC: 'cr',
  CRO: 'hr',
  CUB: 'cu',
  CUW: 'cw',
  CYP: 'cy',
  CZE: 'cz',
  COD: 'cd',
  DEN: 'dk',
  DJI: 'dj',
  DMA: 'dm',
  DOM: 'do',
  ECU: 'ec',
  EGY: 'eg',
  SLV: 'sv',
  ENG: 'gb-eng',
  EQG: 'gq',
  ERI: 'er',
  EST: 'ee',
  SWZ: 'sz',
  ETH: 'et',
  FRO: 'fo',
  FIJ: 'fj',
  FIN: 'fi',
  FRA: 'fr',
  GAB: 'ga',
  GAM: 'gm',
  GEO: 'ge',
  GER: 'de',
  GHA: 'gh',
  GIB: 'gi',
  GRE: 'gr',
  GRN: 'gd',
  GUM: 'gu',
  GUA: 'gt',
  GUI: 'gn',
  GNB: 'gw',
  GUY: 'gy',
  HAI: 'ht',
  HON: 'hn',
  HKG: 'hk',
  HUN: 'hu',
  ISL: 'is',
  IND: 'in',
  IDN: 'id',
  IRN: 'ir',
  IRQ: 'iq',
  ISR: 'il',
  ITA: 'it',
  CIV: 'ci',
  JAM: 'jm',
  JPN: 'jp',
  JOR: 'jo',
  KAZ: 'kz',
  KEN: 'ke',
  KVX: 'xk',
  KUW: 'kw',
  KGZ: 'kg',
  LAO: 'la',
  LVA: 'lv',
  LIB: 'lb',
  LES: 'ls',
  LBR: 'lr',
  LBY: 'ly',
  LIE: 'li',
  LTU: 'lt',
  LUX: 'lu',
  MAC: 'mo',
  MAD: 'mg',
  MWI: 'mw',
  MAS: 'my',
  MDV: 'mv',
  MLI: 'ml',
  MLT: 'mt',
  MTN: 'mr',
  MRI: 'mu',
  MEX: 'mx',
  MDA: 'md',
  MNG: 'mn',
  MNE: 'me',
  MSR: 'ms',
  MAR: 'ma',
  MOZ: 'mz',
  MYA: 'mm',
  NAM: 'na',
  NEP: 'np',
  NED: 'nl',
  NCL: 'nc',
  NZL: 'nz',
  NCA: 'ni',
  NIG: 'ne',
  NGA: 'ng',
  PRK: 'kp',
  MKD: 'mk',
  NIR: 'gb-nir',
  NOR: 'no',
  OMA: 'om',
  PAK: 'pk',
  PLE: 'ps',
  PAN: 'pa',
  PNG: 'pg',
  PAR: 'py',
  PER: 'pe',
  PHI: 'ph',
  POL: 'pl',
  POR: 'pt',
  PUR: 'pr',
  QAT: 'qa',
  IRL: 'ie',
  ROU: 'ro',
  RUS: 'ru',
  RWA: 'rw',
  SKN: 'kn',
  LCA: 'lc',
  VIN: 'vc',
  SAM: 'ws',
  SMR: 'sm',
  KSA: 'sa',
  SCO: 'gb-sct',
  SEN: 'sn',
  SRB: 'rs',
  SEY: 'sc',
  SLE: 'sl',
  SGP: 'sg',
  SVK: 'sk',
  SVN: 'si',
  SOL: 'sb',
  SOM: 'so',
  RSA: 'za',
  KOR: 'kr',
  SSD: 'ss',
  ESP: 'es',
  SRI: 'lk',
  SDN: 'sd',
  SUR: 'sr',
  SWE: 'se',
  SUI: 'ch',
  SYR: 'sy',
  STP: 'st',
  TAH: 'pf',
  TPE: 'tw',
  TJK: 'tj',
  TAN: 'tz',
  THA: 'th',
  TLS: 'tl',
  TOG: 'tg',
  TGA: 'to',
  TRI: 'tt',
  TUN: 'tn',
  TUR: 'tr',
  TKM: 'tm',
  TCA: 'tc',
  USA: 'us',
  UGA: 'ug',
  UKR: 'ua',
  UAE: 'ae',
  VIR: 'vi',
  URU: 'uy',
  UZB: 'uz',
  VAN: 'vu',
  VEN: 've',
  VIE: 'vn',
  WAL: 'gb-wls',
  YEM: 'ye',
  ZAM: 'zm',
  ZIM: 'zw',
}

/** Subdivision flag emoji (tag sequences) — fall back to 🇬🇧 where unsupported. */
const SUBDIVISION_EMOJI: Record<string, string> = {
  'gb-eng': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'gb-sct': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'gb-wls': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'gb-nir': '🇬🇧',
}

/** ISO alpha-2 → regional indicator flag emoji. */
export function isoToFlagEmoji(iso: string): string | null {
  const key = iso.trim().toLowerCase()
  if (SUBDIVISION_EMOJI[key]) return SUBDIVISION_EMOJI[key]
  if (!/^[a-z]{2}$/.test(key)) return null
  const cps = [...key.toUpperCase()].map((c) => 0x1f1e6 - 65 + c.charCodeAt(0))
  return String.fromCodePoint(...cps)
}

export function flagEmojiFromFifa(code: string | null | undefined): string | null {
  if (!code) return null
  const iso = FIFA_TO_ISO[code.trim().toUpperCase()]
  if (!iso) return null
  return isoToFlagEmoji(iso)
}

/** @deprecated use flagEmojiFromFifa — kept for any leftover imports */
export function flagSlugFromFifa(code: string | null | undefined): string | null {
  if (!code) return null
  return FIFA_TO_ISO[code.trim().toUpperCase()] ?? null
}

export function flagUrl(slug: string, height = 20): string {
  const h = height <= 20 ? 20 : height <= 40 ? 40 : 80
  return `https://flagcdn.com/h${h}/${slug}.png`
}
